begin;

select plan(24);

select is(
  (select count(*)::integer
   from pg_trigger
   where tgrelid = 'public.profiles'::regclass
     and tgname = 'profiles_set_updated_at'),
  1,
  'profiles has the server timestamp trigger'
);
select is(
  (select count(*)::integer
   from pg_trigger
   where tgrelid = 'public.band_members'::regclass
     and tgname = 'band_members_prevent_last_owner'),
  1,
  'band members have the last owner trigger'
);
select is(
  (select count(*)::integer
   from pg_trigger
   where tgrelid = 'public.profiles'::regclass
     and tgname = 'profiles_anonymize_references'),
  1,
  'profiles have the anonymization trigger'
);
select is(
  (select count(*)::integer
   from pg_trigger
   where tgrelid = 'public.shows'::regclass
     and tgname = 'shows_require_editable_state'),
  1,
  'shows have the read-only state trigger'
);
select is(
  (select count(*)::integer
   from pg_trigger
   where tgrelid = 'public.show_items'::regclass
     and tgname = 'show_items_song_band_check'),
  1,
  'show items validate their band references'
);

do $$
declare
  owner_id uuid := '00000000-0000-0000-0000-000000000082';
  member_id uuid := '00000000-0000-0000-0000-000000000083';
  guest_id uuid := '00000000-0000-0000-0000-000000000084';
  other_band_id uuid := '00000000-0000-0000-0000-000000000085';
  band_id uuid := '00000000-0000-0000-0000-000000000086';
  song_id uuid := '00000000-0000-0000-0000-000000000087';
  other_song_id uuid := '00000000-0000-0000-0000-000000000088';
  show_id uuid := '00000000-0000-0000-0000-000000000089';
  block_id uuid := '00000000-0000-0000-0000-000000000090';
begin
  insert into auth.users (id, aud, role, email)
  values
    (owner_id, 'authenticated', 'authenticated', 'task-4-6-owner@example.test'),
    (member_id, 'authenticated', 'authenticated', 'task-4-6-member@example.test'),
    (guest_id, 'authenticated', 'authenticated', 'task-4-6-guest@example.test');
  insert into public.profiles (id, display_name)
  values
    (owner_id, 'Owner 4.6'),
    (member_id, 'Member 4.6'),
    (guest_id, 'Guest 4.6')
  on conflict (id) do update
  set display_name = excluded.display_name;
  insert into public.bands (id, name)
  values
    (band_id, 'Banda de teste 4.6'),
    (other_band_id, 'Outra banda 4.6');
  insert into public.band_members (band_id, user_id, role)
  values
    (band_id, owner_id, 'owner'),
    (band_id, member_id, 'member'),
    (band_id, guest_id, 'member');
  insert into public.songs (id, band_id, title)
  values
    (song_id, band_id, 'Música da banda 4.6'),
    (other_song_id, other_band_id, 'Música de outra banda');
  insert into public.shows (id, band_id, name, starts_at, venue)
  values (show_id, band_id, 'Show de teste 4.6', '2026-11-01 21:00:00+00', 'Palco 4.6');
  insert into public.show_blocks (id, show_id, name, position)
  values (block_id, show_id, 'Principal', 0);
  insert into public.show_items (block_id, position, item_type, song_id)
  values (block_id, 0, 'song', song_id);
  insert into public.legal_acceptances (band_id, user_id, term_version)
  values (band_id, guest_id, '2026-01');
  insert into public.invitations (
    band_id,
    token_hash,
    created_by,
    used_by
  )
  values (
    band_id,
    encode(extensions.digest('task-4-6-anonimizar', 'sha256'), 'hex'),
    owner_id,
    guest_id
  );
end;
$$;

do $$
begin
  perform pg_sleep(0.01);
end;
$$;

update public.profiles
set display_name = 'Owner 4.6 atualizado', updated_at = timestamp '2000-01-01';
update public.bands
set name = 'Banda de teste 4.6 atualizada', updated_at = timestamp '2000-01-01';
update public.songs
set notes = 'Atualização de teste', updated_at = timestamp '2000-01-01';
update public.shows
set notes = 'Atualização de teste', updated_at = timestamp '2000-01-01';
update public.show_blocks
set name = 'Principal atualizado', updated_at = timestamp '2000-01-01';
update public.show_items
set notes = 'Observação atualizada', updated_at = timestamp '2000-01-01';

select ok(
  (select updated_at > timestamp '2026-01-01' from public.profiles
   where id = '00000000-0000-0000-0000-000000000082'),
  'profile timestamp is generated by the server'
);
select ok(
  (select updated_at > timestamp '2026-01-01' from public.bands
   where id = '00000000-0000-0000-0000-000000000086'),
  'band timestamp is generated by the server'
);
select ok(
  (select updated_at > timestamp '2026-01-01' from public.songs
   where id = '00000000-0000-0000-0000-000000000087'),
  'song timestamp is generated by the server'
);
select ok(
  (select updated_at > timestamp '2026-01-01' from public.shows
   where id = '00000000-0000-0000-0000-000000000089'),
  'show timestamp is generated by the server'
);
select ok(
  (select updated_at > timestamp '2026-01-01' from public.show_blocks
   where id = '00000000-0000-0000-0000-000000000090'),
  'block timestamp is generated by the server'
);
select ok(
  (select updated_at > timestamp '2026-01-01'
   from public.show_items
   where block_id = '00000000-0000-0000-0000-000000000090' and position = 0),
  'item timestamp is generated by the server'
);

select throws_ok(
  $$delete from public.band_members
    where band_id = '00000000-0000-0000-0000-000000000086'
      and user_id = '00000000-0000-0000-0000-000000000082'$$,
  'P0001',
  null,
  'the last owner cannot leave a band with other members'
);
select throws_ok(
  $$update public.band_members
    set role = 'member'
    where band_id = '00000000-0000-0000-0000-000000000086'
      and user_id = '00000000-0000-0000-0000-000000000082'$$,
  'P0001',
  null,
  'the last owner cannot be demoted'
);
update public.band_members
set role = 'owner'
where band_id = '00000000-0000-0000-0000-000000000086'
  and user_id = '00000000-0000-0000-0000-000000000083';
delete from public.band_members
where band_id = '00000000-0000-0000-0000-000000000086'
  and user_id = '00000000-0000-0000-0000-000000000082';
select is(
  (select count(*)::integer from public.band_members
   where band_id = '00000000-0000-0000-0000-000000000086'
     and role = 'owner'),
  1,
  'a band keeps another owner before the original owner leaves'
);

update public.shows
set status = 'ready'
where id = '00000000-0000-0000-0000-000000000089';
select throws_ok(
  $$update public.shows
    set venue = 'Palco alterado'
    where id = '00000000-0000-0000-0000-000000000089'$$,
  'P0001',
  null,
  'ready shows are read-only'
);
select throws_ok(
  $$update public.show_blocks
    set name = 'Bloco alterado'
    where id = '00000000-0000-0000-0000-000000000090'$$,
  'P0001',
  null,
  'blocks of ready shows are read-only'
);
select throws_ok(
  $$update public.show_items
    set notes = 'Nota alterada'
    where block_id = '00000000-0000-0000-0000-000000000090'
      and position = 0$$,
  'P0001',
  null,
  'items of ready shows are read-only'
);
update public.shows
set status = 'draft'
where id = '00000000-0000-0000-0000-000000000089';
update public.show_blocks
set name = 'Bloco reaberto'
where id = '00000000-0000-0000-0000-000000000090';
select is(
  (select name from public.show_blocks
   where id = '00000000-0000-0000-0000-000000000090'),
  'Bloco reaberto',
  'returning a show to draft re-enables editing'
);

select throws_ok(
  $$insert into public.show_items (block_id, position, item_type, song_id)
    values (
      '00000000-0000-0000-0000-000000000090',
      1,
      'song',
      '00000000-0000-0000-0000-000000000088'
    )$$,
  'P0001',
  null,
  'setlist songs must belong to the show band'
);

select throws_ok(
  $$delete from auth.users
    where id = '00000000-0000-0000-0000-000000000083'$$,
  'P0001',
  null,
  'account deletion cannot remove the last remaining owner'
);

delete from auth.users
where id = '00000000-0000-0000-0000-000000000084';
select is(
  (select count(*)::integer from public.bands
   where id = '00000000-0000-0000-0000-000000000086'),
  1,
  'deleting a profile preserves the band'
);
select is(
  (select count(*)::integer from public.legal_acceptances
   where band_id = '00000000-0000-0000-0000-000000000086'
     and user_id is null),
  1,
  'legal authorship is anonymized after profile deletion'
);
select is(
  (select count(*)::integer from public.invitations
   where band_id = '00000000-0000-0000-0000-000000000086'
     and created_by = '00000000-0000-0000-0000-000000000082'::uuid
     and used_by is null),
  1,
  'consumption references are anonymized while authorship remains'
);

delete from auth.users
where id = '00000000-0000-0000-0000-000000000083';
delete from auth.users
where id = '00000000-0000-0000-0000-000000000082';
select is(
  (select count(*)::integer from public.invitations
   where band_id = '00000000-0000-0000-0000-000000000086'
     and created_by is null),
  1,
  'creator references are anonymized after account deletion'
);

select * from finish();

rollback;
